version: "3"

services:
  node:
    build: .

    container_name: xp-api

    working_dir: /app

    volumes:
      - ./:/app

    ports:
      - 8000:8000

    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_DATABASE: xp-db

  
  db:
    image: mysql:8.0.21

    container_name: xp-db

    restart: always

    ports:
      - 3306:3306

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
